Models/ErrorViewModel.cs
namespace MVC_Example.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace MVC_Example.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        public ActionResult Index()
        {
            string[] files = Directory.GetFiles("TextFiles").Select(file =>
                Path.GetFileNameWithoutExtension(file)).ToArray();
            return View(files);
        }

        public ActionResult Content(string id)
        {
            string[] content = System.IO.File.ReadAllLines(Directory.GetCurrentDirectory() +
                "/TextFiles/" + id + ".txt");
            return View(content);
        }
    }
}

Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace MVC_Example.Controllers
{
    public class FilesController : Controller
    {
        // GET: File
        public ActionResult Index()
        {
            string[] files = Directory.GetFiles("TextFiles").Select(file =>
                Path.GetFileNameWithoutExtension(file)).ToArray();
            ViewData["fileNames"] = files;
            return View(files);
        }

        public ActionResult Content(string id)
        {
            string[] content = System.IO.File.ReadAllLines(Directory.GetCurrentDirectory() +
                "/TextFiles/" + id + ".txt");
            return View(content);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVC_Example.Models;

namespace MVC_Example.Controllers;

//Name of controller
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    //constructor
    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        string[] days = {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"};
        ViewData["days"] = days;
        return View();
    }

    public IActionResult Privacy()
    {
        //returns home/index.cshtml
        return View();
    }

    public IActionResult Bogus()
    {
        //Viewdata and Viewbag are interchangeable 
        ViewData["author"] = "John Cena";
        ViewBag.Date = DateTime.Now;
        string[] days = {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"};
        return View(days);
    }

    //called if error
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProcessController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MVC_Example.Controllers
{
    public class ProcessController : Controller
    {
        // GET: Process
        public ActionResult Index()
        {
            return View(Process.GetProcesses());
        }

        public ActionResult Display(int id) 
        {
            return View(Process.GetProcessById(id));
        }
    }
}

Views/File/Index.cshtml
@{
    ViewData["Title"] = "Files";
    string[]? fileNames = ViewData["fileNames"] as string[];
}

<div class="text-center">
    <h2>@ViewData["Title"]</h2>
    <ul>
        @foreach (var item in fileNames!)
        {
            <li>
                <a asp-controller="File" asp-action="Content"
                    asp-route-id="@item">@item</a>
            </li>
        }
    </ul>
</div>

Views/Files/Content.cshtml
@{
    ViewData["Title"] = "File Contents";
}

<div>
    @foreach (var item in Model)
    {    
        <p asp-controller="File" asp-route-id="@item">@item</p>
    }
</div>

Views/Files/Index.cshtml
@{
    ViewData["Title"] = "Text Files";
    string[]? fileNames = ViewData["fileNames"] as string[];
}

<div class="text-center">
    <h2>@ViewData["Title"]</h2>
    <ul>
        @foreach (var item in fileNames!)
        {
            <li>
                <a asp-controller="Files" asp-action="Content"
                    asp-route-id="@item">@item</a>
            </li>
        }
    </ul>
</div>

Views/Home/Bogus.cshtml
@model string[] 
@{
    ViewData["Title"] = "Bogus Page";
    //var date = (System.DateTime) ViewData["Date"]!; 
    var date = (System.DateTime) ViewBag.Date;
}
<h1>@ViewData["Title"]</h1>

<p>This is my first ASP.NET page authored by @ViewData["author"] on @date.ToShortDateString().</p>

<ul>
    @foreach (var item in Model)
    {
        <li>@item</li>
    }
</ul>

Views/Home/Index.cshtml
<!-- C# island -->
@{
    ViewData["Title"] = "Home Page";
    string[]? days = ViewData["days"] as string[];
}

<div class="text-center">
    <h1 class="display-4" style="color: tomato">Welcome to COMP4870</h1>
    <h2> Name: Valerie Tan</h2>
    <h2> Student Number: A01288758</h2>
    <h2> Job: No idea, I'll take whatever job I can get in the beginning</h2>
</div>

Views/Process/Display.cshtml
@model System.Diagnostics.Process
@{
    ViewData["Title"] = "Process Details";
}

<div>
    <table>
        <tr>
            <td>ID</td>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <td>Name</td>
            <td>@Model.ProcessName</td>
        </tr>
        <tr>
            <td>Count</td>
            <td>@Model.HandleCount</td>
        </tr>
    </table>
</div>

Views/Process/Index.cshtml
@model System.Diagnostics.Process[]
@{
    ViewData["Title"] = "Proccesses";
}

<div class="text-center">
    <h2>@ViewData["Title"]</h2>
    <ul>
        @foreach (var item in Model)
        {
            <li>
                <a asp-controller="Process" asp-action="Display"
                    asp-route-id="@item.Id">@item.ProcessName</a>
            </li>
        }
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Example</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Example.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Example</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Bogus">Bogus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Files" asp-action="Index">Text Files</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- injection point for views -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC_Example - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>